# north ^ y
#       |
# west  |    east
#-------+--------> x
#       |
# south |
#
[[room]]
pos="0,0,0"
description="the room"
north="you have a mirror"
west="a PC with two screens :desktop: :desktop:"
south="a couch :couch:"
exits="ns"
[[room]]
pos="0,1,0"
description="the corridor"
north="""a sign 'Mika's Favorite Avatars\n
Mika did not make them'"""
exits="nes"
[[room]]
pos="1,1,0"
description="the corridor"
north="""a sign 'Pictures'"""
exits="nw"
[[room]]
pos="0,2,0"
description="the avatar room"
exits="s"
[[room]]
pos="1,2,0"
description="the room with pictures"
north=":frame_photo: :frame_photo: :frame_photo: :frame_photo: :frame_photo: :frame_photo:"
east=":frame_photo: :frame_photo: :frame_photo: :frame_photo: :frame_photo: :frame_photo:"
south=":frame_photo: :frame_photo: :frame_photo: :frame_photo: :frame_photo: :frame_photo:"
west=":frame_photo: :frame_photo: :frame_photo: :frame_photo: :frame_photo: :frame_photo:"
exits="s"
[[room]]
pos="0,-1,0"
description="the place next to the door"
east="button :black_square_button: and the door"
exits="ne"
[[room]]
pos="1,-1,0"
description="the trail"
west="button and door"
exits="w"
